/**
 * Ambient type augmentations for the Workers test environment.
 *
 * `@cloudflare/workers-types` declares `env` (from `cloudflare:workers`) as
 * `Cloudflare.Env`, which starts as an empty interface.  Normally
 * `worker-configuration.d.ts` (generated by `wrangler types`) augments it,
 * but that file lives outside the TypeScript `include` path and is gitignored,
 * so it is absent on a clean checkout.
 *
 * This file augments `Cloudflare.Env` directly so that test code is fully
 * typed without requiring provisioned infrastructure.  When
 * `worker-configuration.d.ts` IS present, TypeScript merges the two
 * declarations — the property types are identical so there is no conflict.
 *
 * Rule: add one entry here for every binding in `wrangler.test.jsonc`.
 */

/** Shape of one migration entry as returned by `readD1Migrations`. */
interface D1MigrationEntry {
	name: string;
	queries: string[];
}

declare namespace Cloudflare {
	interface Env {
		/** D1 database binding — Miniflare provisions an in-memory SQLite instance. */
		DB: D1Database;
		/** Injected by vitest config via `miniflare.bindings`; never in production. */
		TEST_MIGRATIONS: D1MigrationEntry[];
		/** Cloudflare Access team domain (test placeholder in wrangler.test.jsonc). */
		CLOUDFLARE_TEAM_DOMAIN: string;
		/** Seed admin e-mail (test placeholder in wrangler.test.jsonc). */
		SEED_ADMIN_EMAIL: string;
	}
}
